// DATOS DE LOS RÓTULOS =======================================================
// Cada entrada está indexada por su "id" (= nombre del archivo sin extensión,
// el mismo que usa la galería en script.js).
//
//   nombre    -> título que se muestra en la cabecera de la ficha
//   original  -> foto original (alta resolución) en ./src/originales/
//   svg       -> trazado vectorial para la animación caligráfica
//                (./src/svg/<id>.svg) — lo añades tú cuando lo tengas
//   ubicacion -> dónde está / estaba el rótulo  ✏️ EDITAR
//   historia  -> un poco de historia del comercio/rótulo  ✏️ EDITAR
//
// Mientras no exista el .svg, la ficha muestra solo la foto original y un aviso.

const ROTULOS = {
  "libreria-papeleria": {
    nombre: "Librería Papelería",
    original: "./src/originales/2016-10_11-LibreriapapeleriaWeb-1.jpg",
    svg: "./src/svg/libreria-papeleria.svg",
    ubicacion: "✏️ Añade aquí la calle / barrio donde se encuentra el rótulo.",
    historia: "✏️ Añade aquí un poco de historia del comercio y del rótulo.",
  },
  "cafe-bar": {
    nombre: "Café Bar",
    original: "./src/originales/2016-10_18-CafeBarWeb.jpg",
    svg: "./src/svg/cafe-bar.svg",
    ubicacion: "✏️ Añade aquí la calle / barrio donde se encuentra el rótulo.",
    historia: "✏️ Añade aquí un poco de historia del comercio y del rótulo.",
  },
  "chocolates": {
    nombre: "Chocolates",
    original: "./src/originales/2016-10_20-ChocolatesWeb.jpg",
    svg: "./src/svg/chocolates.svg",
    ubicacion: "✏️ Añade aquí la calle / barrio donde se encuentra el rótulo.",
    historia: "✏️ Añade aquí un poco de historia del comercio y del rótulo.",
  },
  "metropol": {
    nombre: "Metropol",
    original: "./src/originales/2016-10_27-MetropolWeb.jpg",
    svg: "./src/svg/metropol.svg",
    ubicacion: "✏️ Añade aquí la calle / barrio donde se encuentra el rótulo.",
    historia: "✏️ Añade aquí un poco de historia del comercio y del rótulo.",
  },
  "congo": {
    nombre: "Congo",
    original: "./src/originales/2016-10_31-CongoWeb.jpg",
    svg: "./src/svg/congo.svg",
    ubicacion: "✏️ Añade aquí la calle / barrio donde se encuentra el rótulo.",
    historia: "✏️ Añade aquí un poco de historia del comercio y del rótulo.",
  },
  "seccion-de-ninos": {
    nombre: "Sección de Niños",
    original: "./src/originales/2016-10_32-SecciondeninosWeb.jpg",
    svg: "./src/svg/seccion-de-ninos.svg",
    ubicacion: "✏️ Añade aquí la calle / barrio donde se encuentra el rótulo.",
    historia: "✏️ Añade aquí un poco de historia del comercio y del rótulo.",
  },
  "estornell": {
    nombre: "Estornell",
    original: "./src/originales/2016-10_56-Estornell1Web.jpg",
    svg: "./src/svg/estornell.svg",
    ubicacion: "✏️ Añade aquí la calle / barrio donde se encuentra el rótulo.",
    historia: "✏️ Añade aquí un poco de historia del comercio y del rótulo.",
  },
  "muebles-sedavi": {
    nombre: "Muebles Sedaví",
    original: "./src/originales/2016-10_69-MueblesSedaviWeb.jpg",
    svg: "./src/svg/muebles-sedavi.svg",
    ubicacion: "✏️ Añade aquí la calle / barrio donde se encuentra el rótulo.",
    historia: "✏️ Añade aquí un poco de historia del comercio y del rótulo.",
  },
  "chocolates-valero": {
    nombre: "Chocolates Valero",
    original: "./src/originales/2016-10_71-ChocolatesValeroWeb.jpg",
    svg: "./src/svg/chocolates-valero.svg",
    ubicacion: "✏️ Añade aquí la calle / barrio donde se encuentra el rótulo.",
    historia: "✏️ Añade aquí un poco de historia del comercio y del rótulo.",
  },
  "la-artistica": {
    nombre: "La Artística",
    original: "./src/originales/2016-10_79-LaArtisticaWeb.jpg",
    svg: "./src/svg/la-artistica.svg",
    ubicacion: "✏️ Añade aquí la calle / barrio donde se encuentra el rótulo.",
    historia: "✏️ Añade aquí un poco de historia del comercio y del rótulo.",
  },
  "ultramarinos": {
    nombre: "Ultramarinos",
    original: "./src/originales/2016-10_114-UltramarinosWeb.jpg",
    svg: "./src/svg/ultramarinos.svg",
    ubicacion: "✏️ Añade aquí la calle / barrio donde se encuentra el rótulo.",
    historia: "✏️ Añade aquí un poco de historia del comercio y del rótulo.",
  },
  "mercat-de-russafa": {
    nombre: "Mercat de Russafa",
    original: "./src/originales/2016-10_118-MercatdeRussafaWeb.jpg",
    svg: "./src/svg/mercat-de-russafa.svg",
    ubicacion: "✏️ Añade aquí la calle / barrio donde se encuentra el rótulo.",
    historia: "✏️ Añade aquí un poco de historia del comercio y del rótulo.",
  },
  "norte-buen-viaje": {
    nombre: "Norte Buen Viaje",
    original: "./src/originales/2016-10_125-NorteBuenViaje3Web.jpg",
    svg: "./src/svg/norte-buen-viaje.svg",
    ubicacion: "✏️ Añade aquí la calle / barrio donde se encuentra el rótulo.",
    historia: "✏️ Añade aquí un poco de historia del comercio y del rótulo.",
  },
  "caminos-hierro-norte": {
    nombre: "Caminos de Hierro del Norte",
    original: "./src/originales/2016-10_127-CaminosHierroNorteWeb.jpg",
    svg: "./src/svg/caminos-hierro-norte.svg",
    ubicacion: "✏️ Añade aquí la calle / barrio donde se encuentra el rótulo.",
    historia: "✏️ Añade aquí un poco de historia del comercio y del rótulo.",
  },
  "correo-oficinas": {
    nombre: "Correo · Oficinas",
    original: "./src/originales/2016-10_127-CorreoOficinasWeb.jpg",
    svg: "./src/svg/correo-oficinas.svg",
    ubicacion: "✏️ Añade aquí la calle / barrio donde se encuentra el rótulo.",
    historia: "✏️ Añade aquí un poco de historia del comercio y del rótulo.",
  },
  "horchateria-santa-catalina": {
    nombre: "Horchatería Santa Catalina",
    original: "./src/originales/2016-12_HorchateriaSantaCatalina2Web.jpg",
    svg: "./src/svg/horchateria-santa-catalina.svg",
    ubicacion: "✏️ Añade aquí la calle / barrio donde se encuentra el rótulo.",
    historia: "✏️ Añade aquí un poco de historia del comercio y del rótulo.",
  },
  "gran-cine-royalty": {
    nombre: "Gran Cine Royalty",
    original: "./src/originales/2017-04_GranCineRoyaltyWeb.jpg",
    svg: "./src/svg/gran-cine-royalty.svg",
    ubicacion: "✏️ Añade aquí la calle / barrio donde se encuentra el rótulo.",
    historia: "✏️ Añade aquí un poco de historia del comercio y del rótulo.",
  },
  "ume-antes-casa": {
    nombre: "UME · Antes Casa",
    original: "./src/originales/2017-11_UME-AntesCasaWeb2.jpg",
    svg: "./src/svg/ume-antes-casa.svg",
    ubicacion: "✏️ Añade aquí la calle / barrio donde se encuentra el rótulo.",
    historia: "✏️ Añade aquí un poco de historia del comercio y del rótulo.",
  },
  "ume-union-musica": {
    nombre: "UME · Unión Musical",
    original: "./src/originales/2017-11_UME-UnionMusicaWeb2.jpg",
    svg: "./src/svg/ume-union-musica.svg",
    ubicacion: "✏️ Añade aquí la calle / barrio donde se encuentra el rótulo.",
    historia: "✏️ Añade aquí un poco de historia del comercio y del rótulo.",
  },
  "bicicletas-prieto": {
    nombre: "Bicicletas E. Prieto",
    original: "./src/originales/2018-03_BicicletasE.PrietoWeb.jpg",
    svg: "./src/svg/bicicletas-prieto.svg",
    ubicacion: "✏️ Añade aquí la calle / barrio donde se encuentra el rótulo.",
    historia: "✏️ Añade aquí un poco de historia del comercio y del rótulo.",
  },
  "papeleria-vila": {
    nombre: "Papelería Vila",
    original: "./src/originales/2018-03_PapeleriaVilaWeb.jpg",
    svg: "./src/svg/papeleria-vila.svg",
    ubicacion: "✏️ Añade aquí la calle / barrio donde se encuentra el rótulo.",
    historia: "✏️ Añade aquí un poco de historia del comercio y del rótulo.",
  },
  "balneario-alameda": {
    nombre: "Balneario Alameda",
    original: "./src/originales/2018-05_BalnearioAlamedaWeb.jpg",
    svg: "./src/svg/balneario-alameda.svg",
    ubicacion: "✏️ Añade aquí la calle / barrio donde se encuentra el rótulo.",
    historia: "✏️ Añade aquí un poco de historia del comercio y del rótulo.",
  },
  "fabrica-conservas": {
    nombre: "Fábrica de Conservas",
    original: "./src/originales/2018-05_FabricaConservasWeb.jpg",
    svg: "./src/svg/fabrica-conservas.svg",
    ubicacion: "✏️ Añade aquí la calle / barrio donde se encuentra el rótulo.",
    historia: "✏️ Añade aquí un poco de historia del comercio y del rótulo.",
  },
  "frutos-secos": {
    nombre: "Frutos Secos",
    original: "./src/originales/2018-05_Frutos-SecosWeb2.jpg",
    svg: "./src/svg/frutos-secos.svg",
    ubicacion: "✏️ Añade aquí la calle / barrio donde se encuentra el rótulo.",
    historia: "✏️ Añade aquí un poco de historia del comercio y del rótulo.",
  },
  "almacenes-espana": {
    nombre: "Almacenes España",
    original: "./src/originales/2018-06_AlmacenesEspanaWeb.jpg",
    svg: "./src/svg/almacenes-espana.svg",
    ubicacion: "✏️ Añade aquí la calle / barrio donde se encuentra el rótulo.",
    historia: "✏️ Añade aquí un poco de historia del comercio y del rótulo.",
  },
  "cinema-colon": {
    nombre: "Cinema Colón",
    original: "./src/originales/2018-06_CinemaColonWeb.jpg",
    svg: "./src/svg/cinema-colon.svg",
    ubicacion: "✏️ Añade aquí la calle / barrio donde se encuentra el rótulo.",
    historia: "✏️ Añade aquí un poco de historia del comercio y del rótulo.",
  },
  "talleres-tintoreria-rodrigo": {
    nombre: "Talleres Tintorería Rodrigo",
    original: "./src/originales/2018-10_TalleresTintoreriaRodrigo5Web.jpg",
    svg: "./src/svg/talleres-tintoreria-rodrigo.svg",
    ubicacion: "✏️ Añade aquí la calle / barrio donde se encuentra el rótulo.",
    historia: "✏️ Añade aquí un poco de historia del comercio y del rótulo.",
  },
  "pescaderia-la-palmera": {
    nombre: "Pescadería La Palmera",
    original: "./src/originales/2019-01_PescaderiaLaPalmeraWeb.jpg",
    svg: "./src/svg/pescaderia-la-palmera.svg",
    ubicacion: "✏️ Añade aquí la calle / barrio donde se encuentra el rótulo.",
    historia: "✏️ Añade aquí un poco de historia del comercio y del rótulo.",
  },
  "muebles-ballester": {
    nombre: "Muebles Ballester",
    original: "./src/originales/2020-01_MueblesBallesterWeb.jpg",
    svg: "./src/svg/muebles-ballester.svg",
    ubicacion: "✏️ Añade aquí la calle / barrio donde se encuentra el rótulo.",
    historia: "✏️ Añade aquí un poco de historia del comercio y del rótulo.",
  },
  "muebles-sabater": {
    nombre: "Muebles Sabater",
    original: "./src/originales/2020-01_MueblesSabaterWeb-1.jpg",
    svg: "./src/svg/muebles-sabater.svg",
    ubicacion: "✏️ Añade aquí la calle / barrio donde se encuentra el rótulo.",
    historia: "✏️ Añade aquí un poco de historia del comercio y del rótulo.",
  },
  "pescaderia-pepe": {
    nombre: "Pescadería Pepe",
    original: "./src/originales/2020-01_PescaderiaPepeWeb.jpg",
    svg: "./src/svg/pescaderia-pepe.svg",
    ubicacion: "✏️ Añade aquí la calle / barrio donde se encuentra el rótulo.",
    historia: "✏️ Añade aquí un poco de historia del comercio y del rótulo.",
  },
  "fontaneria": {
    nombre: "Fontanería",
    original: "./src/originales/2020-03_FontaneriaWeb.jpg",
    svg: "./src/svg/fontaneria.svg",
    ubicacion: "✏️ Añade aquí la calle / barrio donde se encuentra el rótulo.",
    historia: "✏️ Añade aquí un poco de historia del comercio y del rótulo.",
  },
  "ferreteria-beaumont": {
    nombre: "Ferretería Beaumont",
    original: "./src/originales/2021-08_FerreteriaBeaumontWeb-1-2.jpg",
    svg: "./src/svg/ferreteria-beaumont.svg",
    ubicacion: "✏️ Añade aquí la calle / barrio donde se encuentra el rótulo.",
    historia: "✏️ Añade aquí un poco de historia del comercio y del rótulo.",
  },
  "la-casa-de-las-pieles": {
    nombre: "La Casa de las Pieles",
    original: "./src/originales/2021-08_La-CasadelasPielesWeb2.jpg",
    svg: "./src/svg/la-casa-de-las-pieles.svg",
    ubicacion: "✏️ Añade aquí la calle / barrio donde se encuentra el rótulo.",
    historia: "✏️ Añade aquí un poco de historia del comercio y del rótulo.",
  },
  "paqueteria-mary": {
    nombre: "Paquetería Mary",
    original: "./src/originales/2022-11_PaqueteriaMaryWeb3.jpg",
    svg: "./src/svg/paqueteria-mary.svg",
    ubicacion: "✏️ Añade aquí la calle / barrio donde se encuentra el rótulo.",
    historia: "✏️ Añade aquí un poco de historia del comercio y del rótulo.",
  },
  "garage-guimera": {
    nombre: "Garaje Guimerá",
    original: "./src/originales/2023-09_GarageGuimeraWeb1-2.jpg",
    svg: "./src/svg/garage-guimera.svg",
    ubicacion: "✏️ Añade aquí la calle / barrio donde se encuentra el rótulo.",
    historia: "✏️ Añade aquí un poco de historia del comercio y del rótulo.",
  },
  "raga": {
    nombre: "Raga",
    original: "./src/originales/2024-01_RagaWeb.jpg",
    svg: "./src/svg/raga.svg",
    ubicacion: "✏️ Añade aquí la calle / barrio donde se encuentra el rótulo.",
    historia: "✏️ Añade aquí un poco de historia del comercio y del rótulo.",
  },
  "la-azulejera-valenciana": {
    nombre: "La Azulejera Valenciana",
    original: "./src/originales/2024-10_LaAzulejeraValencianaWeb-0.jpg",
    svg: "./src/svg/la-azulejera-valenciana.svg",
    ubicacion: "✏️ Añade aquí la calle / barrio donde se encuentra el rótulo.",
    historia: "✏️ Añade aquí un poco de historia del comercio y del rótulo.",
  },
  "3m-wmditer": {
    nombre: "3M · WMditer",
    original: "./src/originales/2025-04_3MWMditerWeb.jpg",
    svg: "./src/svg/3m-wmditer.svg",
    ubicacion: "✏️ Añade aquí la calle / barrio donde se encuentra el rótulo.",
    historia: "✏️ Añade aquí un poco de historia del comercio y del rótulo.",
  },
  "marieta": {
    nombre: "Marieta",
    original: "./src/originales/marieta.png",
    svg: "./src/svg/marieta.svg",
    ubicacion: "✏️ Añade aquí la calle / barrio donde se encuentra el rótulo.",
    historia: "✏️ Añade aquí un poco de historia del comercio y del rótulo.",
  },
  "bastian-barber": {
    nombre: "Bastian Barber",
    original: "./src/originales/bastian-barber.png",
    svg: "./src/svg/bastian-barber.svg",
    ubicacion: "✏️ Añade aquí la calle / barrio donde se encuentra el rótulo.",
    historia: "✏️ Añade aquí un poco de historia del comercio y del rótulo.",
  },
};

// Disponible como window.ROTULOS (lo usa rotulo.js)
window.ROTULOS = ROTULOS;
